(() => {
  const menu = document.querySelector('[data-menu]');
  const drawer = document.querySelector('[data-menu-drawer]');
  menu?.addEventListener('click', () => { drawer.hidden = !drawer.hidden; });
  drawer?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { drawer.hidden = true; }));
  const root = document.querySelector('[data-studio]');
  if (!root) return;
  const $ = (selector) => root.querySelector(selector);
  const $$ = (selector) => [...root.querySelectorAll(selector)];
  const state = {primary:'#f4f6f4',secondary:'#121512',accent:'#9cff00',material:'Standard Vinyl',coverage:'Full',overlay:'none',text:'',textColor:'#ffffff',notes:'',zoom:1,logo:'',logoScale:90};
  let history = [];
  let future = [];
  let toastTimer;
  const prices = {'Partial|Standard Vinyl':39500,'Full|Standard Vinyl':59500,'Partial|Chrome':69500,'Full|Chrome':89500,'Partial|Holographic':69500,'Full|Holographic':89500};
  const format = (cents) => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(cents/100);
  const snapshot = () => JSON.stringify({...state,logo:''});
  const historyButtons = () => { $('[data-undo]').disabled=!history.length;$('[data-redo]').disabled=!future.length; };
  const push = () => { history.push(snapshot());if(history.length>40)history.shift();future=[];historyButtons(); };
  const notify = (text) => { const toast=$('[data-toast]');toast.textContent=text;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800); };
  const price = () => prices[`${state.coverage}|${state.material}`] || 59500;
  const render = () => {
    root.style.setProperty('--primary',state.primary);
    root.style.setProperty('--secondary',state.secondary);
    root.style.setProperty('--accent',state.accent);
    root.dataset.overlay=state.overlay;
    root.dataset.material=state.material;
    root.dataset.coverage=state.coverage;
    $('[data-canvas]').style.transform=`scale(${state.zoom})`;
    $('[data-zoom]').textContent=`${Math.round(state.zoom*100)}%`;
    $('.custom-text').textContent=state.text;
    $('.custom-text').style.fill=state.textColor;
    const logo=$('[data-logo-preview]');
    logo.src=state.logo;
    logo.hidden=!state.logo;
    logo.style.width=`${state.logoScale*1.55}px`;
    ['primary','secondary','accent'].forEach((key)=>{const input=$(`[data-color="${key}"]`);if(input)input.value=state[key];const label=input?.parentElement.querySelector('b');if(label)label.textContent=state[key];});
    const total=format(price());
    $('[data-price]').textContent=total;$('[data-add-price]').textContent=total;$('[data-breakdown-price]').textContent=total;
    $('[data-breakdown-material]').textContent=state.material;$('[data-breakdown-coverage]').textContent=state.coverage;
    $$('[data-material]').forEach((button)=>button.classList.toggle('active',button.dataset.material===state.material));
    $$('[data-coverage]').forEach((button)=>button.classList.toggle('active',button.dataset.coverage===state.coverage));
    $$('[data-overlay]').forEach((button)=>button.classList.toggle('active',button.dataset.overlay===state.overlay));
  };
  const mutate = (fn) => { push();fn();render(); };
  $$('[data-tab]').forEach((button)=>button.addEventListener('click',()=>{
    const key=button.dataset.tab;
    $$('[data-panel]').forEach((panel)=>{panel.hidden=panel.dataset.panel!==key;});
    $('[data-panel-wrap]').hidden=false;
    $$('[data-tab]').forEach((item)=>item.classList.toggle('active',item===button));
  }));
  $('[data-panel-close]').addEventListener('click',()=>{ $('[data-panel-wrap]').hidden=true;$$('[data-tab]').forEach((item)=>item.classList.remove('active')); });
  $$('[data-preset]').forEach((button)=>button.addEventListener('click',()=>{
    const values=button.dataset.preset.split(',');
    mutate(()=>{[state.primary,state.secondary,state.accent]=values;});
    $$('[data-preset]').forEach((item)=>item.classList.toggle('active',item===button));
  }));
  $$('[data-color]').forEach((input)=>{
    input.addEventListener('input',()=>{state[input.dataset.color]=input.value;render();});
    input.addEventListener('change',()=>mutate(()=>{state[input.dataset.color]=input.value;}));
  });
  $$('[data-material]').forEach((button)=>button.addEventListener('click',()=>mutate(()=>{state.material=button.dataset.material;})));
  $$('[data-coverage]').forEach((button)=>button.addEventListener('click',()=>mutate(()=>{state.coverage=button.dataset.coverage;})));
  $$('[data-overlay]').forEach((button)=>button.addEventListener('click',()=>mutate(()=>{state.overlay=button.dataset.overlay;})));
  $('[data-text]').addEventListener('input',(event)=>{state.text=event.target.value;render();});
  $('[data-text-color]').addEventListener('input',(event)=>{state.textColor=event.target.value;render();event.target.parentElement.querySelector('b').textContent=event.target.value;});
  $('[data-notes]').addEventListener('input',(event)=>{state.notes=event.target.value;});
  $('[data-logo]').addEventListener('change',(event)=>{const file=event.target.files?.[0];if(!file)return;mutate(()=>{state.logo=URL.createObjectURL(file);});});
  $('[data-logo-scale]').addEventListener('input',(event)=>{state.logoScale=Number(event.target.value);render();});
  $('[data-logo-remove]').addEventListener('click',()=>mutate(()=>{if(state.logo)URL.revokeObjectURL(state.logo);state.logo='';$('[data-logo]').value='';}));
  $('[data-zoom-in]').addEventListener('click',()=>mutate(()=>{state.zoom=Math.min(1.5,state.zoom+.1);}));
  $('[data-zoom-out]').addEventListener('click',()=>mutate(()=>{state.zoom=Math.max(.7,state.zoom-.1);}));
  const mixes={stealth:['#e6eae6','#0b0e0c','#9cff00','hex'],ocean:['#78d6f7','#072f49','#f1f7f8','stripes'],race:['#f4f5f3','#101311','#ff2d2d','stripes'],fire:['#ff5a1f','#130b07','#ffd23f','hex'],luxury:['#e7dfcf','#151713','#b7a369','none']};
  const randomMix=()=>Object.values(mixes)[Math.floor(Math.random()*Object.values(mixes).length)];
  const useMix=(mix)=>mutate(()=>{[state.primary,state.secondary,state.accent,state.overlay]=mix;});
  $('[data-random]').addEventListener('click',()=>useMix(randomMix()));
  $('[data-generate]').addEventListener('click',()=>{const prompt=$('[data-mix-prompt]').value.toLowerCase();const key=Object.keys(mixes).find((name)=>prompt.includes(name));useMix(key?mixes[key]:randomMix());notify('DESIGN MIX APPLIED');});
  $('[data-undo]').addEventListener('click',()=>{if(!history.length)return;future.push(snapshot());Object.assign(state,JSON.parse(history.pop()));historyButtons();render();});
  $('[data-redo]').addEventListener('click',()=>{if(!future.length)return;history.push(snapshot());Object.assign(state,JSON.parse(future.pop()));historyButtons();render();});
  const dialogs=$$('dialog');
  $$('[data-dialog-close]').forEach((button)=>button.addEventListener('click',()=>button.closest('dialog').close()));
  $('[data-model]').addEventListener('click',()=> $('[data-model-dialog]').showModal());
  $('[data-model-continue]').addEventListener('click',()=>{ $('[data-model-dialog]').close();notify(`${$('[data-year]').value} · ${$('[data-model-select]').value} SELECTED`);});
  $('[data-price-info]').addEventListener('click',()=> $('[data-price-dialog]').showModal());
  const storage='trix-preview-builds';
  const getBuilds=()=>{try{return JSON.parse(localStorage.getItem(storage)||'[]');}catch{return[];}};
  const renderBuilds=()=>{const list=$('[data-build-list]');const builds=getBuilds();if(!builds.length){list.innerHTML='<p>NO SAVED BUILDS YET</p>';return;}list.innerHTML=builds.map((build,index)=>`<div class="saved"><div><b>${build.name}</b><small>${new Date(build.date).toLocaleDateString()}</small></div><button data-load="${index}">LOAD</button><button data-delete="${index}">×</button></div>`).join('');list.querySelectorAll('[data-load]').forEach((button)=>button.addEventListener('click',()=>{Object.assign(state,builds[Number(button.dataset.load)].state);render();$('[data-builds-dialog]').close();}));list.querySelectorAll('[data-delete]').forEach((button)=>button.addEventListener('click',()=>{builds.splice(Number(button.dataset.delete),1);localStorage.setItem(storage,JSON.stringify(builds));renderBuilds();}));};
  $('[data-save]').addEventListener('click',()=>{const builds=getBuilds();builds.unshift({name:`VOLTAGE ${builds.length+1}`,date:new Date().toISOString(),state:JSON.parse(snapshot())});localStorage.setItem(storage,JSON.stringify(builds.slice(0,10)));notify('BUILD SAVED');});
  $('[data-builds]').addEventListener('click',()=>{renderBuilds();$('[data-builds-dialog]').showModal();});
  $('[data-add]').addEventListener('click',()=>{document.querySelector('[data-cart] b').textContent='1';notify('CONFIGURED WRAP ADDED TO CART');});
  dialogs.forEach((dialog)=>dialog.addEventListener('click',(event)=>{if(event.target===dialog)dialog.close();}));
  render();historyButtons();
})();
